### ISSUE TITLE
can't download package

### ISSUE THREAD

**Issue by Alejo199** [atom-ide-community/atom-script#1053] opened 2016-08-24 14:11 UTC
i've been constantly trying to download the file to run my javascript projects, but it constantly keeps telling me that i'm unable to download due some sort of connection to github
the message is the following:

```
npm ERR! git clone --template=/Users/alexgonzalez/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /Users/alexgonzalez/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository '/Users/alexgonzalez/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=/Users/alexgonzalez/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /Users/alexgonzalez/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: unable to connect to github.com:
npm ERR! git clone --template=/Users/alexgonzalez/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /Users/alexgonzalez/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: github.com[0: 192.30.253.112]: errno=Operation timed out
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/alexgonzalez/Downloads/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/alexgonzalez/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/alexgonzalez/.atom/.apm/.apmrc" "--userconfig" "/Users/alexgonzalez/.atom/.apmrc" "install" "/private/var/folders/p2/cjg7x9y116517d_81w03hmfc0000gn/T/d-116724-25998-upx4ox/package.tgz" "--target=0.37.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! nam  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/Users/alexgonzalez/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=Operation timed out
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/p2/cjg7x9y116517d_81w03hmfc0000gn/T/apm-install-dir-116724-25998-3ssjj3/npm-debug.log

```

thanks for the help

**Comment by jonathanrjpereira** [comment] 2016-08-25 07:08
I have the same problem.
I am running:

- Windows 10

- Atom 1.9.9

- Electron 0.37.8

- Chrome 49.0.2623.75

- Node 5.10.0

- npm 2.14.20


I was trying to install the 'Script' Package

**Comment by kitaniboy** [comment] 2016-08-26 05:51
I have the same problem.
I am running:
Windows 10 also
please give me the answer

**Comment by kitaniboy** [comment] 2016-08-26 05:53
Installing “script@3.9.0” failed.Hide output…
Failed to install script because Git was not found.

The script package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com

Run apm -v after installing Git to see what version has been detected.

**Comment by nixel2007** [comment] 2016-08-26 06:53
@rgbkrk
> npm ERR! error: cannot spawn sh: No such file or directory

Do we have some hardcoded "sh" call during installation?

**Comment by iamolivinius** [comment] 2016-09-22 17:12
Looks like duplicate of https://github.com/rgbkrk/atom-script/issues/1062 and should be related to https://github.com/rburns/ansi-to-html/issues/27

**Closed** 2020-12-29 19:39 UTC
Labels: duplicate
