### ISSUE TITLE
Fails to install on Atom

### ISSUE THREAD

**Issue by jsquardo** [atom-ide-community/atom-script#1010] opened 2016-07-18 15:31 UTC
Im trying to install this script in Atom but I keep getting an error...

Installing “script@3.8.2” failed.Hide output…

npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git://github.com/monsterkodi/node-simple-plist.git resetting remote C:\Users\Johnny.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\Johnny.atom.apm_git-remotes_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Johnny.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository 'C:\Users\Johnny.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=C:\Users\Johnny.atom.apm_git-remotes_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Johnny.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\Johnny.atom.apm_git-remotes_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Johnny.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: github.com[0: 192.30.253.112]: errno=No error
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\Johnny\AppData\Local\atom\app-1.8.0\resources\app\apm\bin\node.exe" "C:\Users\Johnny\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Johnny\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Johnny\.atom\.apmrc" "install" "C:\Users\Johnny\AppData\Local\Temp\d-116618-9892-15twx4b\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\Johnny.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=No error
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by scrawfor** [comment] 2016-07-25 18:33
I'm having this same issue.

**Comment by jbinard** [comment] 2016-08-03 14:10
Same issue for me. I'm behind a corporate proxy, it can be related (but others atom plugin are working).
I will try at home later.

**Comment by Akumetsu-Dev** [comment] 2016-08-10 14:32
Hello, i found the solution, first GitHub windows Client not installed completely, what i mean the next step below, the installation process had to do it automatic, but did not.

1- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_<Serial>, in this folder you will find a batch named post-install you have to install it with admin permission.

2- Add to the environment variable the next path:
- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\usr\bin
- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\etc\ssh
- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\cmd
                    *GitHub didnt do this after the instalation, you have to do it manual.
![image](https://cloud.githubusercontent.com/assets/7697566/17557424/248b2978-5ee5-11e6-8e68-36bea6692561.png)

3- In the C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\cmd, you will find 2 *.cmd files: "start-ssh-agent" and "start-ssh-pageant" run in with admin permission.
![image](https://cloud.githubusercontent.com/assets/7697566/17557449/3e3469ac-5ee5-11e6-94a6-2054c0fd363a.png)

4- Reboot windows and try install script.

**Comment by iamolivinius** [comment] 2016-09-22 17:50
Duplicate of #1062 ?!

Doesn't look like a missing git executable.

**Closed** 2020-12-30 04:32 UTC
Labels: installation, please-try-the-latest-version
