### ISSUE TITLE
Add Selection Based support for Java

### ISSUE THREAD

**Issue by jaredleekatzman** [atom-ide-community/atom-script#759] opened 2016-01-28 15:03 UTC
##### Platform: `darwin`

---

I am trying to use the Script package to run Java code. And any time I use Cmd-I to run the file, I get the following error: 

"Selection Based runner not available for Java."

What confuses me is is that no code is selected. I am trying to run the entire script. 
What could the problem be?

**Comment by EntilZha** [comment] 2016-02-12 07:32
Can you provide exact steps to reproduce, a minimal example file of what it breaks on, and screenshots/gifs of what you are doing?

**Comment by EntilZha** [comment] 2016-02-12 07:36
Marking as duplicate of #796, but will keep open since it might actually be a bug of thinking that it should execute as selection based

**Comment by JJ-Atkinson** [comment] 2016-02-17 17:10
I'm having the same issue. Steps to reproduce:

 - Open a new file
 - Set the file type to java
 - Add some code
 - Try to run script

If the file isn't saved it will print
```
Selection Based runner not available for Java.

If it should exist, add an issue on GitHub, or send your own pull request.

^C
```

If it is saved in `file.java` it launches the command line in my home directory, and when I exit the console the error appears in the atom error console.

**Closed** 2020-12-29 18:52 UTC
Labels: Add support for X, duplicate
